version: "1.0"
info:
  model: int-scaffold
packages:
- name: FLOW_TEST_P1Project
  gitServerName: ibm
  gitUrl: https://github.com/Pooja-Anand-IBM-2
  gitUsername: Pooja-Anand-IBM-2
  gitBranch: main
- name: rahs_gl-ispackage
  gitServerName: GL_SH_Account
  gitUrl: http://engx.gitlab01.eur.ad.sag/root
  gitUsername: root
  gitBranch: main
