version: "1.0"
info:
  model: int-scaffold
packages:
- name: FLOW_TEST_P1Project
  gitServerName: ibm
  gitUrl: https://github.com/Pooja-Anand-IBM-2
  gitUsername: Pooja-Anand-IBM-2
  gitBranch: main
